### ISSUE TITLE
Triple-click (select line) does not work

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#3052]
**Imported issue:**

* Author: Chris Elsworth
* Date: 2012-03-08 14:17:47
* Legacy ID: 3122
* Version: 1.4.8

**Steps to reproduce:**  
  
1. Left-click 3 times in rapid succession in any window with a cursor (iTerm, Terminal, XCode)  
  
Expected: The entire line is selected  
Actual: Only the current word you are clicking over is selected  
  
**Versions (Synergy, OS):**  
  
Server: XUbuntu 11.10 (Synergy 1.4.5)  
Client 1: OSX 10.7.3 (Synergy 1.4.8)

**Comment by mabott** [comment]
I've been hitting this but not realizing it until recently.

Synergy 1.6.2, client: OSX 10.9.5, server: windows 7

I code and use terminal a lot, and double-click-then-drag is pretty standard for me. The expected behavior is to highlight the word I double-click, then keep highlighting as I drag the mouse. It does not work on the mac in this setup. If I use a pointing device connected directly to the OSX machine it works as expected. Swapping the client and server is something I will try soon.

nbolton, I would love a hacked release that works properly if you have the cycles to deliver it.

**Comment by jankcat** [comment]
This issue affects everyday workflow use, like selecting blocks of text in a browser, dismissing notifications in Yosemite, copying blocks of text in emails, etc. Definitely a deal breaker for me as a customer. This makes the software unusable for me.

**Comment by jankcat** [comment]
PR #4261 potentially fixes this, but has not been looked at.

**Comment by nbolton** [comment]
@jankcat Please could you try this build? http://synergy-project.org/nightly?filter=pr-jpmcmu-tripple-click-fix

**Comment by jankcat** [comment]
Before: https://jankcat.com/public/synergy/original.mov
After: https://jankcat.com/public/synergy/fix.mov
It seems to work. :+1:

**Comment by nbolton** [comment]
@jankcat Awesome! Thanks for testing and thanks for the movs!

**Comment by jankcat** [comment]
No problem!

**Comment by nbolton** [comment]
Fixed by #4261
