### ISSUE TITLE
Synergy "steals" my keyboard events

### ISSUE THREAD

**Issue by majtejn** [synergy/synergy#4350]
I use Autohotkey and with Synergy turned on, even if no one is connected a large set of hotkeys don't work.

**Comment by nbolton** [comment]
I'm not sure we can fix this, since Synergy and Autohotkey conflict.

**Comment by Squelch** [comment]
I'm unable to pinpoint exactly what the problem is, but Synergy does appear to either swallow keypress events, or maintains a stuck state particularly with modifier keys (Shift, Control, Alt) when run as server on Win 7.  This seems to cause issues with other software. 

The Games Kerbal Space Program and Space Engineer suffer in different ways. With KSP, the shift key (throttle up in flight scene, zoom modifier in editor) does not work while Synergy Server is running. 

Space Engineers suffers a complete keyboard lockout and does not receive keypress events. The only option is to Alt-Tab and close the game.

SwapScreen (part of the Dual Monitor Tools suite) which was an excellent bedfellow to synergy on a multimonitor setup also suffers from strange behaviour. The cursor is locked to one screen and a modifier key is used to unlock it and enter the second screen. With Synergy server running, the cursor is initially locked, but once once any modifier key is pressed, SwapScreen acts as though it is being held, The default modifier has been Ctrl until recently, but can now be re-assigned. The behaviour of any modifier triggering unlock when Synergy is running remains regardless of assignment.

All of these applications were working properly in synergy (sorry) with Synergy server until fairly recently.

Using Debug1 logging, the keystates are being registered by Synergy while the other applications are focussed, but they do not seem to be passed through. 

Here is a log excerpt starting with the mouse event leaving the editing of this message and pressing Shift, Ctrl and Alt respectively.

DEBUG1: event: button press button=1
DEBUG1: onMouseDown id=1
DEBUG1: event: button release button=1
DEBUG1: onMouseUp id=1

[Shift]
DEBUG1: hook: 0x000000a0 0x002a0001
DEBUG1: hook: 0x060000a0 0x002a0001
DEBUG1: hook: 0x070000a0 0x002a0001
DEBUG1: event: Key char=0, vk=0xa0, nagr=0, lParam=0x002a0001
DEBUG1: new mask: 0x2000
DEBUG1: new mask: 0x2001
DEBUG1: onKeyDown id=61409 mask=0x2001 button=0x002a
DEBUG1: hook: 0x000000a0 0x802a0001
DEBUG1: hook: 0x060000a0 0x802a0001
DEBUG1: hook: 0x070000a0 0x802a0001
DEBUG1: event: Key char=0, vk=0xa0, nagr=0, lParam=0x802a0001
DEBUG1: new mask: 0x2001
DEBUG1: new mask: 0x2000
DEBUG1: onKeyUp id=61409 mask=0x2000 button=0x002a
DEBUG1: hook: 0x000000a2 0x001d0001
DEBUG1: hook: 0x060000a2 0x001d0001
DEBUG1: hook: 0x070000a2 0x001d0001

[Ctrl]
DEBUG1: event: Key char=0, vk=0xa2, nagr=0, lParam=0x001d0001
DEBUG1: new mask: 0x2000
DEBUG1: new mask: 0x2002
DEBUG1: onKeyDown id=61411 mask=0x2002 button=0x001d
DEBUG1: hook: 0x000000a2 0x801d0001
DEBUG1: hook: 0x060000a2 0x801d0001
DEBUG1: hook: 0x070000a2 0x801d0001
DEBUG1: event: Key char=0, vk=0xa2, nagr=0, lParam=0x801d0001
DEBUG1: new mask: 0x2002
DEBUG1: new mask: 0x2000
DEBUG1: onKeyUp id=61411 mask=0x2000 button=0x001d
DEBUG1: hook: 0x000000a4 0x20380001
DEBUG1: hook: 0x060000a4 0x20380001
DEBUG1: hook: 0x070000a4 0x20380001

[Alt]
DEBUG1: event: Key char=0, vk=0xa4, nagr=0, lParam=0x20380001
DEBUG1: new mask: 0x2000
DEBUG1: new mask: 0x2004
DEBUG1: onKeyDown id=61417 mask=0x2004 button=0x0038
DEBUG1: hook: 0x000000a4 0x80380001
DEBUG1: hook: 0x060000a4 0x80380001
DEBUG1: hook: 0x070000a4 0x80380001
DEBUG1: event: Key char=0, vk=0xa4, nagr=0, lParam=0x80380001
DEBUG1: new mask: 0x2004
DEBUG1: new mask: 0x2000
DEBUG1: onKeyUp id=61417 mask=0x2000 button=0x0038

[Return to message]
DEBUG2: dragging filename is cleared
DEBUG1: event: button press button=1
...

It is interesting to note that there are no hook log entries after the last onKeyUp for the Alt key. This is also true if the other keys are pressed in isolation followed by a mouse event. I believe this to relevant as in the case of SwapScreen, entering the second monitor will allow a mouse button press to be registered on that screen and then the cursor immediately jumps back to the first monitor as though it is still locked. The inference here is that the hooks are deferred in in being released. This may have a bearing on the interaction with the other applications that are affected. The problem is present only for the server. The same machine acting a a client behaves normally.

The Synergy setup I have that is affected by this:

Synergy Server running on Win7 dual monitor. Primary right, with an extended desktop secondary left. SwapScreen controls the cursor movement between monitors. 

Synergy Client running on Ubuntu 15.04 right of server.
Synergy Client  running on Win7 or Linux (dualboot) above server.

**Comment by dieseltravis** [comment]
Synergy and Autohotkey work well together for me for a few minutes then my hotkey script stops working until I stop/start Synergy again. Is there something from the logs that I could provide that could help?
