### ISSUE TITLE
Automate extract and compile for OpenSSL

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4412]
Right now you have to extract and compile OpenSSL manually (which is painful). This should be done by the toolchain during conf and/or build.

**Comment by XinyuHou** [comment]
Here are some references about how to compile OpenSSL

Windows:
http://developer.covenanteyes.com/building-openssl-for-visual-studio/

Mac OSX
https://gist.github.com/tmiz/1441111

The link for OSX is even for universal binary

**Comment by nbolton** [comment]
Configure and compile instructions...

Windows 64-bit:

1. Visual Studio x64 Cross Tools Command Prompt (2010)
2. perl Configure VC-WIN64A
3. ms\do_win64a
4. nmake -f ms\ntdll.mak

Windows 32-bit:

1. Visual Studio Command Prompt (2010)
2. http://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D
3. perl Configure VC-WIN32
4. ms\do_nasm
5. nmake -f ms\ntdll.mak

Mac OS X:

1. ./configure
2. make

**Comment by ac3d912** [comment]
If people are having trouble building the ns plugin in Windows (because of openssl)...

\> cd <path_to_synergy_git_clone>
\> mkdir ext\openssl\inc32\openssl
\> python
from glob import glob
import os.path
import shutil
for h in glob(r'.\ext\openssl\include\openssl\*.h'):
   with open(h,'r') as fd:
     lnk = fd.read()
   shutil.copy(os.path.abspath(os.path.join(base,lnk)),os.path.abspath(r'.\ext\openssl\inc32\openssl'))
   
-------------------

Also, to compile openssl, I also had to follow this:
http://stackoverflow.com/questions/7680189/openssl-cant-build-in-vc-2010

**Comment by nbolton** [comment]
@speaker Thinking of releasing tomorrow, how's this one coming along?

**Comment by nbolton** [comment]
@XinyuHou?

**Comment by XinyuHou** [comment]
Merged 1c5ade982e9f70a22608d7c52ac48ff8ab143572

**Comment by pdecat** [comment]
Did you mean to commit all those Windows binaries in the ext/openssl-win32/out32dll and ext/openssl-win64/out32dll folders?

**Comment by pdecat** [comment]
The same goes for the Mac OS X binaries in ext/openssl-osx.

**Comment by nbolton** [comment]
@pdecat It was @speaker's idea. It appeared to be the most economical solution. Do you have any thoughts?
