### ISSUE TITLE
OSX client modifier keys stick

### ISSUE THREAD

**Issue by zorrobyte** [synergy/synergy#4604]
Often from my Windows 8 server to my OSX 10.10 client, my modifier keys will get stuck (control, option, command) and the only fix is to repeatedly mash them until they unstick. This has been an issue for at least 2-3 years since I've used Synergy.

I'm currently running 1.7.1

**Comment by zorrobyte** [comment]
Same issue as https://github.com/synergy/synergy/issues/4057

**Comment by beporter** [comment]
There is [a nightly build available](https://github.com/synergy/synergy/pull/4564#issuecomment-95926896) that may help fix this issue. I believe it's slated to be included in an upcoming release.

Since there are already multiple duplicates of this same issue open elsewhere, it might be wise to close this one.

**Comment by nbolton** [comment]
@zorrobyte I guess @beporter's link helped?

**Comment by zorrobyte** [comment]
So far it seems to be working. There was a "fix" build I used a few months back that still had the bug intermittently (used 10 hours a day for work). I will update as I use this build more.

**Comment by nbolton** [comment]
Good luck!
