### ISSUE TITLE
Allow software to be time limited with serial key

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4716]
Problem: Users want a time limited trail version so they can try out our software before buying.

Solution: After implementing #4715 (which should contain an *account expiry date* which can be `null`) we should allow the GUI to show a "Trial expired, please purchase." message and then quit when an *account expiry date* is exceeded. This seems to be allowed by the GPLv2, so long as everything remains open source and we don't restrict redistribution or modification.

**Comment by nbolton** [comment]
@legonigel Can you see any GPLv2 issues with doing this? We get asked every day for a time limited trial "version", so we're only giving people what they want... but I feel like there will be some GPL or open source fanatics that will have something negative to say about this. Any comments?

**Comment by legonigel** [comment]
@nbolton as far as I can tell the GPLv2 should allow this. The only way that the GPLv2 limits the software is that the source must be available for anyone who has a binary version and requests it, and any derivatives must share the same license. This would apply to trial versions as well, so as long as you make available the source code of the trial version to anyone who downloads the trial version you should be okay. Since this project is open source, there is no issue here. 

I do wish to make sure those of us downloading the source and compiling ourselves will still have the freedom to run the software without a key. 

Note: I am not an expert on the GPL, this is just my interpretation based on the language inside the GPLv2. None of this reply constitutes legal advice, and should not be taken as such.

**Comment by kdoteu** [comment]
Works for me:
OS: Windows 64bit
Version: synergy-v1.8.1-beta-f7377d6

Expired Key:
![image](https://cloud.githubusercontent.com/assets/3602457/16535416/5f142daa-3fe7-11e6-8ab5-f5f2381f198e.png)
--> no ns.dll file

Valid Key: ns.dll is loaded

**Comment by Verequies** [comment]
Works as expected, when activated with valid key, it downloads the ns.dll plugin.
![issue 4716 test 1](https://cloud.githubusercontent.com/assets/282071/16537705/62e5851c-404d-11e6-85fb-94d445089e91.png)

Expired message shows when trying to activate with valid key, and the ns.dll plugin does not get downloaded.
![issue 4716 test 2](https://cloud.githubusercontent.com/assets/282071/16537707/75500038-404d-11e6-9373-310b7a8667a6.png)

**Comment by Zygislovas** [comment]
System information:
Windows 10 Enterprise x64
Windows 8.1 Pro x64
Using invalid key gives following warning and ns.dll isn't downloaded. Using valid - no warning, ns.dll was downloaded.
![image](https://cloud.githubusercontent.com/assets/20255330/16540215/0c391716-4065-11e6-9eae-72f8eaad6db1.png)

**Comment by yidhoe** [comment]
Works for me.

**Comment by agraciag** [comment]
Please could you share instructions to reproduce, after unninstalling my licensed synergy, installing the beta grabs the license details and configuration so I don't know how to try to activate again. I did delete plugins folder from user and also tried to delete both, from windows/user and from synergy path.
Thanks. Alex

**Comment by cletsimon** [comment]
OSX 10.10.5
looks good
![screen shot 2016-07-03 at 7 26 40 pm](https://cloud.githubusercontent.com/assets/5573468/16545164/450cd506-4154-11e6-9ab9-77006988cd4b.png)
