### ISSUE TITLE
synergyd.exe uses a lot of CPU

### ISSUE THREAD

**Issue by Cheesebaron** [synergy/synergy#4744]
Updated to 1.7.3 stable today from 1.7.2 and now I see that synergyd.exe uses around 12-14% CPU continuously.

The machine is the client, while I have a Mac which is the Server. I am running with SSL disabled.

![Imgur](http://i.imgur.com/nZLNu7U.png)

There is no indication in the log on what is wrong and sometimes after opening the Synergy UI on Windows it stops using so much CPU.

**Comment by slalomsk8er** [comment]
I see the same symptoms with Synergy Pro 1.7.3 with SSL enabled on Windows 7 64 Bit.
CPU is around 25% only for Synergy an my HP EliteBook 820 with a i7-4500.
The fan noise stops right after opening the Synergy UI and CPU usage drops to around 0%, 1% or 2% (switching between the values). After closing the UI CPU usage stays down for now till next reboot.

**Comment by KrunchMuffin** [comment]
same here. Windows 8.1 Pro (server) and Home (client)

[Client Computer Screenshot](http://i.imgur.com/KbPfzxr.png)

[Server Computer Screenshot](http://i.imgur.com/cqnPu2k.png)

**Comment by XinyuHou** [comment]
Duplicated to #4721. Please check the nightly posted in #4721

**Comment by XinyuHou** [comment]
Could anyone test this nightly?

http://synergy-project.org/nightly?filter=bd3a8

**Comment by vanowm** [comment]
BD3A8 nightly seems to fix this issue, though it brought other issues along:
Upon install the GUI windows showed "start" button, as if service wasn't started, yet it was. On server clicking start button seems to work as expected, but after restarting GUI it still shows start button, instead of apply/stop.
On client computer same issue, except clicking start button kills the service, with popup message "Please fill a host name for the synergy client to connect to", aka auto config no longer works. Entered server's name and then enabled auto config again - it starts fine. and restarting GUI shows correctly apply/stop buttons, unlike server.

**Comment by DavidMoffatt-At-Nokia-com** [comment]
A quick and dirty way to stop this is to open the synergy UI and leave it open.   You can minimize it to keep it out of your way.   My win box is my server and it dropped the CPU usage from 25% to 0 or 1%.
No bad effects of doing this.  No need to worry about using a beta build.   Hope they fix this soon.

**Comment by hyungjic** [comment]
Experiencing the same problem and DavidMoffat's workaround works. Thanks!

**Comment by fuzzzerd** [comment]
I have the same issue described here, and I too am able to bring down the CPU usage by launching the Synergy GUI. No negative side effects so far from doing this, but it would be nice to have an actual fix.

**Comment by afroznissar** [comment]
I have the same issue as well. Leaving the Synergy GUI open brought down the CPU usage. Thanks for the workaround David!

**Comment by XinyuHou** [comment]
Duplicates  #4721

New nightly should solve this issue.

http://synergy-project.org/nightly?filter=2de27
