### ISSUE TITLE
WARNING: large clipboards not supported with ssl

### ISSUE THREAD

**Issue by fuzzzerd** [synergy/synergy#4753]
What is the size limit for clipboards with SSL, and why is it different than without?

**Comment by XinyuHou** [comment]
This is related #4712.

SSL limits its record size to 16k. 

https://www.openssl.org/docs/ssl/SSL_write.html

**Comment by fuzzzerd** [comment]
So is there a way that clipboard transfers could be done in 16kb chunks to fully facilitate any size clipboard? Using SSL is nice for the protection; however, the lack of ability to copy pictures (or large text) across is rather limiting to the SSL feature.

That other issue is "closed" as well, but it appears that the fix, was to simply display a warning in the server? Are there plans to remove this limitation in the future?

**Comment by XinyuHou** [comment]
@fuzzzerd 
#4712 is not closed. Github is a bit confusing. The close tags are for the duplicated ticket.

What we do in the next release is split clipboard into small chunks that SSL can handle, then assemble them on the other side. So clipboard and drag and drop would work as before. There is a nightly ready for test if you are interested. Please leave comment in #4712 since this is duplicated.
