### ISSUE TITLE
Ctrl+Alt+Del won't get transferred from a Windows 8.1 server to a Windows 7 client

### ISSUE THREAD

**Issue by SLanghammer** [synergy/synergy#4756]
I'm  trying to log in on a Windows 7 Professional, where Synergy runs as client, using a Windows 8.1 Pro with the Synergy server on it. 
When I try to unlock the win7 screen using Ctrl+Alt+Del, with the mouse arrow being on the win7 screen, win8.1 reacts instead.

**Comment by wlritchi** [comment]
By design, Windows will not let a program detect or simulate Ctrl+Alt+Del. This is in fact the purpose of requiring it to unlock the screen; a program disguised as a login screen will not be able to accurately simulate the real one. Unfortunately, this means that it's unlikely that Synergy can work around the issue.

**Comment by beporter** [comment]
Many programs use an alternate key combination to simulate this though. It's definitely possible to simulate. Virtualbox uses <kbd>Cmd-Del</kbd> (or <kbd>Win-Del</kbd>) to send <kbd>Ctrl-Alt-Del</kbd> into the VM, for example. RDC uses <kbd>Ctrl-Alt-End</kbd>.

Obviously in those cases you're working with a "simulated" environment on the other side, but there must be some way of specifying a key combination that Synergy takes to mean "send Ctrl-Alt-Del to the screen I'm currently on". (While <kbd>Ctrl-Alt-Del</kbd> will **always** be intercepted and interpreted locally by the OS, if it's Windows.)

**Comment by tomicjr** [comment]
A solution is available in the [FAQ] (https://github.com/synergy/synergy/wiki/Synergy-FAQ#why-doesnt-ctrlaltdel-work-on-secondary-screens).

**Ctrl + Alt + Pause/Break** is working for me.

I also defined hotkeys in the configuration file to set focus using the keyboard:

`keystroke(Control+KP_1) = switchToScreen(SYSTEM1)`
`keystroke(Control+KP_3) = switchToScreen(SYSTEM2)`

Note: If you find you cannot switch screens, often it is because Scroll Lock was pressed.  This tripped me up when I was experimenting to find a key sequence to unlock the client screen!

**Comment by speaker** [comment]
Thank you for the link and explanations, @tomicjr and @wlritchi 

@SLanghammer , @beporter Did the FAQ help relieve your issue?

**Comment by Mr-GQ** [comment]
@tomicjr When I click on the FAQ I am being sent to a link to create a new page. I cannot see the instructions on how to solve this issue.

**Comment by tomicjr** [comment]
Try this link:

https://github.com/synergy/synergy/wiki/User-FAQ#Why_doesnt_CtrlAltDel_work_on_secondary_screens
