### ISSUE TITLE
Rapid movements in a fullscreen application minimizes it

### ISSUE THREAD

**Issue by pitastrudl** [synergy/synergy#4767]
I've reinstalled my windows 7 and started having the following problem.

Both server and client are win7 64bit, updated to latest synergy. When on server, and in a fullscreen application like Borderlands video game or Counter Strike, rapid mouse movements minimize the application. I can see the cursor going to my second screen and to the synergy client.

**Comment by speaker** [comment]
@pitastrudl , Arg, I hate that too!

This is a side effect of what synergy does, and there is an easy workaround. Hit the "Scroll Lock" key on the server and it will prevent the mouse from moving from the current machine. Alternately run in windowed mode maximized to full screen and the mouse will still move off to the other machine but the application will not fall back.

The effect of "falling back" like that is not synergy, it's the OS and the application. The same thing happens if the app looses focus with ctrl-alt-del or the windows key as well.
