### ISSUE TITLE
Copy Paste from Chrome(Server) to Client not working

### ISSUE THREAD

**Issue by tarres** [synergy/synergy#4783]
Copying a text from Chrome on the Synergy Server Machine and pasting it on a Mac Client is not working.
Strangely this happens when I want to copy a normal text, copying from an input field (like the one used to create this issue) works.

Synergy Version 1.7.3 (all Machines)
Server: Windows 7 x64
Client; Mac OS 10.10
Chrome 43.0.2357.81

**Comment by beporter** [comment]
Oh so many possible duplicates/related issues: https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

Chrome doesn't necessarily treat text in a text field as "plain" since CSS can still be applied to it. Does copy/pasting work from a purely "plaintext" program like Notepad? For example: If you can copy from Chrome to Notepad _on the same machine_, then re-copy from Notepad and paste on the other Synergy-connected computer, then the issue is with Synergy copying rich text still and is a duplicate of at least #2909.

**Comment by tarres** [comment]
Yeah it does not work with other rich text snippets as well, so it's copy from  #2909 . Didn't find that because i only searched for chrome.
