### ISSUE TITLE
clipboard doesn't work

### ISSUE THREAD

**Issue by cybermails** [synergy/synergy#4788]
The clipboard feature used to work when I first set Synergy up on my computers. But now it just doesn't work both to and from server/client. I have tried restarting both servers and clients, reinstalling synergy, etc. Nothing has worked. The mouse and keyboard work just fine, however the clipboard is kaput.

**Comment by beporter** [comment]
Please see here: https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

**Comment by beporter** [comment]
If one of those other threads describes the issue you're having, you can subscribe to them to get emailed updates and close this one as a duplicate.

If you think your issue is distinct from those, can you please post additional information on your operating systems, the versions of Synergy you're using, and the specific circumstances under which the clipboard fails? Have you tried copying and pasting from different programs? Notepad versus Chrome? Have you tried a small amount of text versus a large amount? Have you tried an image instead of text? Have you tried disabling the SSL feature in Synergy? All of these things will help the developers and the rest of community here narrow down the source of your issue. Thanks!
