### ISSUE TITLE
"Handle Leak in Thread synergys.exe(5188): 4104" in Version 1.7.3 and 1.7.4

### ISSUE THREAD

**Issue by stubweb** [synergy/synergy#4876]
I have experienced a "Handle Leak" using Process Explorer to detect the handle count in Thread synergys.exe(5188): 4104 by simply moving the mouse between windows.  3 handles are lost between every window switch.  It occurs on both systems Windows 7 and a Windows XP system.  I see the behavior in version 1.7.3 Stable and 1.7.4 nightly builds.  The system freezes after a day or two because it is out of resources.

![synergy](https://cloud.githubusercontent.com/assets/13371281/8735793/17591bec-2bd9-11e5-98b4-d8026a49c487.PNG)

**Comment by XinyuHou** [comment]
Duplicates https://github.com/synergy/synergy/issues/3335

**Comment by galkinvv** [comment]
This is about *thread* handles leak, but #3335 is about *event* handle leaks, so this bug was closed in error, and I think shold be reopened - problem persists in current master and in  https://github.com/synergy/synergy/commit/3eaefcfaf366e59bc03c0e517c7959ab90bd6eca

It can be easily reproduced by moving mouse between screens - each move adds a new thread handle in process explorer (windows).

Also I expirience similar problem with linux server. Running 32-bit synergy on amd64 kernel every move between screens increases virtual memory (but not resident) by a 20 MB - it is stack of finished but  not detached thread. After ~200 movements between screens synergys crashes with "cannot create thread" message.

Investigation shows that threads created in client and server are waited but not detached https://github.com/synergy/synergy/commit/cf5347c8f6cae16559678838d280433f97941908#commitcomment-14101052
