### ISSUE TITLE
ERROR: failed to init synwinhk.dll, another program may be using it

### ISSUE THREAD

**Issue by surfer190** [synergy/synergy#4951]
ERROR: failed to init synwinhk.dll, another program may be using it

I restarted. Something is going on here, just updated to latest versions (1.7.3 linux client)
(1.7.4) windows client

**Comment by Cpuroast** [comment]
Usually, the simplest way to fix that is to restart the Windows synergy service

**Comment by the-wes** [comment]
duplicates #4957

**Comment by willianma** [comment]
We also are having the synwinhk.dll issue in Windows 10 x64 machines. Sometimes OneNote, explorer.exe, eclipse.exe and SynTPEnh.exe(synaptics touchpad software) are using it. The problem happens when some process is using it, but that's normal, several processes should be able to access the same dll. and they do so.. but sometimes Synergy Pro 1.7.4 (latest build) is troubling it. In some cases it fixes itself after some time, so that I don't have to kill all common sharing processes..

**Comment by uowis** [comment]
Same bug, i watch this issue from several month, nothing ?

**Comment by darkdragon-001** [comment]
same problem here...

**Comment by brandonrisell** [comment]
I run into this problem almost daily and must reboot my machine to fix it. Any word on the cause and/or fix?

Running Synergy Pro v1.7.5 on Windows 10 Home 64-bit.

**Comment by spronkey** [comment]
I get this error at least once per day, after Synergy crashes (usually due to a clipboard error). Today, it was the windows update exe using the DLL (wtf), and even after killing said EXE, and restarting the synergy windows service, it's still giving me errors.

I'm running 1.7.6 pro on Win7 x64 server, and OS X el cap client, same version of synergy.

**Comment by ybotspawn** [comment]
For those dealing with this problem.  I just got tired of dealing with it.  Stop the synergy server service and all synergy processes.  Next, download process explorer (https://download.sysinternals.com/files/ProcessExplorer.zip) and find all processes using the symwinhk.dll (usually dwm.exe and rundll).  Right click on each and restart.  When you search against symwinhk.dll again you should get no results.  After that you should be able to start the synergy service and synergy without issue and without rebooting.
