### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Sorunome** [synergy/synergy#5002]
Is it possible to add FreeBSD support? The version you install with "pkg install synergy" is way out-of-date, version 1.6.2 (Doesn't even seem to support encryption :/ )
When trying to build v1,7,4-rc8 manually it just gives me "Error: Unsupported platform: freebsd10"

EDIT: Just stumbled upon the builds here which only provide the command-line tools: http://portsmon.freebsd.org/portoverview.py?category=sysutils&portname=synergy
and for crypto apparently there is --enable-crypto which synergyc --help doesn't show. Also it currently can't find the ns plugin, but I guess I still have to install some package for that then.

**Comment by tagg** [comment]
According to the log files, the FreeBSD synergy port has been at version 1.7.4 since 2015-08-13 06:33:29. You may want to investigate why your pkg tries to install old versions.

If you have issues with FreeBSD ports, please submit a problem report at https://bugs.freebsd.org/bugzilla/enter_bug.cgi - that is much more likely to get you a relevant response.

**Comment by Sorunome** [comment]
Ok, thank you, I guess I'll close it now.
