### ISSUE TITLE
Win 7: pressing CTRL+ALT+DEL in client acts on server (although Software SAS enabled!)

### ISSUE THREAD

**Issue by teelittle** [synergy/synergy#5097]
#### setup 
I have two machines running Win 7 Pro x64: 
* A (synergy server): member in a Server 2012 R2 domain 
* B (synergy client): member in a Server 2003 R2 domain 

#### issue 
Both `WIN`+`L` and `CTRL`+`ALT`+`DEL` are routed to machine A, so there is no way to login / lock / unlock machine B. 
This happens although "Software SAS" is enabled on machine B! 

#### steps taken to resolve the issue 
I found out that there is a windows policy called `Disable or enable software Secure Attention Sequence (SAS)` (available since Vista) which must be configured in a way that certain events (like `CTRL`+`ALT`+`DEL`) can be simulated by software (i.e. services and/or "Ease of access" applications). 
As the relevant group policy is unknown on Windows Server 2003 R2, I installed "RSAT" on the Win 7 machine (including Group Policy Management Console), then executed `gpmc.msc` on the Win 7 machine under a domain administrator account and used it to create a new group policy object (named `Synergy-GPO`) which sets the domain policy [`Disable or enable software Secure Attention Sequence`](https://www.vanstechelman.eu/windows-group-policy-encyclopedia/1be4cb01fd5efdb8c4a95005de3bab6d/disable-or-enable-software-secure-attention-sequence) to `enable services and EoA applications to simulate SAS` and linked to that object from the "Computers" group in the domain. 
I finally copied the relevant `.admx` files from the Win 7 machine to the central policy repository on the Win2K3 server as described in [MSDN:Managing Group Policy ADMX Files] (https://msdn.microsoft.com/en-us/library/bb530196.aspx) so they get distributed as "foreign policies" by the Win2K3 server to all clients. 

Checking on the client machine, I find the registry key `HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System!SoftwareSASGeneration` correctly set to value "3", so **the client seems to be prepared like described in [Wiki / FAQ / CtrlAltDel on secondary screens] (https://github.com/synergy/synergy/wiki/User-FAQ#Why_doesnt_CtrlAltDel_work_on_secondary_screens)**

**Comment by teelittle** [comment]
sorry,  forgot to mention synergy version: 

both machines are running **latest stable 1.7.4 (x64)** binaries, communication is left unencrypted.

**Comment by the-wes** [comment]
please see https://github.com/synergy/synergy/wiki/User-FAQ#Why_doesnt_CtrlAltDel_work_on_secondary_screens, specifically this note:

On Windows servers, Ctrl+Alt+Del is always intercepted by Windows and is never passed to Synergy. We have implemented Ctrl+Alt+Pause/Break as a workaround, which will send a ctrl+alt+del sequence across to the client.

**Comment by teelittle** [comment]
Hi the-wes! 
Thank you for responding so fast. However, I have to object closing this issue: 

I do have two Windows 7 machines, no server OS running (they are just members in domains where the DC is a server OS).
Having read the FAQ mentioned by you, I have tried `Ctrl`+`Alt`+`Pause/Break`, and it did do nothing (should it do anything on non-server OS'es??). 

I am afraid your hint does not apply in my case, does it?

**Comment by the-wes** [comment]
I'm not sure where your focus on the OS being a "server" variety or not comes from. Perhaps there is confusion with using the term "server" - it is used in a lot of different ways. In this case we're referring to the Synergy server, meaning the computer which has the keyboard and mouse plugged into it which you're using for both computers via Synergy.

When you press ctrl+alt+pause, is your mouse focused on the client at that time? That is a requirement in order for this to work.

If that does not work, please double and triple-check that the SAS-from-software is enabled on the client. This is very hard to get right, and very easy to get wrong, so it's important to check very carefully.

Additionally, and this may be the key missing bit now that I think about it, because of the way Windows works, this can only be used to _UNLOCK_ a system. It cannot be used to lock a system, because Windows will not accept an SAS or a Win+L from a normal software process, no matter what policy settings are in effect. It will only accept these (SAS/Win+L) from an elevated process, which Synergy does automagically when there is a lock screen or SAS prompt displayed. You can tell Synergy to be elevated all the time (Edit -> Settings) but this breaks other things like file and clipboard sharing. So you just have to choose which one to sacrifice.

I've seen some users create an icon on the desktop which locks the screen. I don't remember how it's done, so I'll let you google for the specifics.

I have somehow been set up to receive notices on all github activity for the Synergy project, so I cannot possibly read all of it. However, I do think keeping this conversation out here where everyone can read it is beneficial. So, if you have any followup and need any further response, please make the comment here, and then email me (wes@the-wes.com) to tell me there's an update.

Regarding closing this bug report - it does need to remain closed as it is not really a bug in Synergy and there is not really anything that can be done about it. If someone finds a way (even theoretical) to alter Windows' behavior in such a way as to facilitate this, I urge them to file a bug report including that information.

Thank you.

**Comment by teelittle** [comment]
Dear wes, 

thanks a lot for taking the time to elaborate on the background of this issue! Indeed, I could have found out some of what you wrote by better *rtfm*, but you helped me to get a deeper understanding of the limitations! 
I am willing to rework the FAQ or write a new wiki section, based on the work you did here, to make synergy behaviour even more transparent to users... 
Can you get me (<my profile name> at gmx,de) in touch with someone responsible to discuss how to best integrate this extended information?

**Comment by the-wes** [comment]
replied via email since there's nothing further specific to this issue in this comment, just about the documentation.

**Comment by teelittle** [comment]
I implemented a way to lock the client machine as follows: 
* create a new shortcut on the client machine's desktop 
* in the link dialog field, enter `rundll32.exe user32.dll, LockWorkStation`
  * this works from WinXP / Win2K3 upwards (for technical reference, see [MSDN: Windows API > System Admin and Management > System Shutdown > S. S. Reference >  S. S. functions > LockWorkStation](https://msdn.microsoft.com/de-de/library/windows/desktop/aa376875%28v=vs.85%29.aspx) )
* enter a name for the desktop shortcut and have the link created 
Customise the shortcut: `ALT+ENTER` or `RMB > Properties`
* in the field `shortcut key`, you might want to enter `AltGr + L` to imitate `WIN + L` (which is intercepted by Windows on the synergy server and won't reach the client machine)
* to have a nice icon, choose `change icon...` and enter `%SystemRoot%\System32\imageres.dll` as the file from which to read icons, then make your choice from the icon set included with that DLL 

Now you can lock your client machine by focusing it and pressing `AltGr + L`
