### ISSUE TITLE
Can't run on OSX, "accessibility features" problem.

### ISSUE THREAD

**Issue by punto-** [synergy/synergy#5172]
I'm using version 1.7.5 on osx 10.10.5. When I try to start synergy, I get a dialog saying "synergy would like to control this computer using accessibility features", so I click on "open system preferences", and enable synergy (it's already enabled actually), close the preferences window (there's no "apply" button or anything, I assume it saves the settings automatically), try to open synergy again, and I get the same message saying I need to change the accessibility settings, It's like it doesn't recognize them.

Posted on the forums, but got no response, so I assume it's not a known issue

**Comment by tjd2002** [comment]
Works for me on 10.11.2, if upgrading your OS is an option :)

I ran into a similar problem when using 'Teleport' from Abyssoft. The fix was to delete the entry in that accessibility list (using the 'minus' button) and let the app re-create it on next launch. 

Also, may want to double-check that you used the 10.10-specific installer ( http://synergy-project.org/download/file?file=synergy-v1.7.5-stable-fa85a24-MacOSX1010-x86_64.dmg )?

**Comment by XinyuHou** [comment]
@punto- 

Please try @tjd2002 suggestion. If it still doesn't work. Try to delete the record directly from system database or contact our help desk.

https://synergy-project.org/contact/ 

http://apple.stackexchange.com/questions/178313/change-accessibility-setting-on-mac-using-terminal
